# name: Build and Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main

# jobs:
#   upload:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repository
#         uses: actions/checkout@v3

#       - name: Upload production-ready build files
#         uses: actions/upload-artifact@v4
#         with:
#           name: github-pages
#           path: dist

#   deploy:
#     needs: upload
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       pages: write
#       contents: read

#     steps:
#       - name: Deploy to GitHub Pages
#         uses: actions/deploy-pages@v4
#         with:
#           artifact_name: github-pages